<?php
/**
 * Published year field for Posts and Publications
 * This function records fields for the acf.
 */
function register_custom_acf_fields_block_button() {
	if ( function_exists( 'acf_add_local_field_group' ) ) {
    acf_add_local_field_group( array(
      'key' => 'group_64de8b8f2e4fe',
      'title' => 'Block Button',
      'fields' => array(
        array(
          'key' => 'field_64de8b8f7c27a',
          'label' => 'Title Button',
          'name' => 'for_title_button',
          'aria-label' => '',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'maxlength' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
        ),
        array(
          'key' => 'field_64de8ba97c27b',
          'label' => 'Button Link',
          'name' => 'for_button_link',
          'aria-label' => '',
          'type' => 'url',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
        ),
        array(
          'key' => 'field_64de8d027c27c',
          'label' => 'Button Style',
          'name' => 'for_button_style',
          'aria-label' => '',
          'type' => 'select',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'btn-primary-small' => 'Primary Small',
            'btn-primary' => 'Primary',
            'btn-primary-large' => 'Primary Large',
            'btn-secondary-small' => 'Secondary Small',
            'btn-secondary' => 'Secondary',
            'btn-secondary-large' => 'Secondary Large',
            'btn-white-small' => 'White Small',
            'btn-white' => 'White',
            'btn-white-large' => 'White Large',
            'btn-dark-small' => 'Dark Small',
            'btn-dark' => 'Dark',
            'btn-dark-large' => 'Dark Large',
          ),
          'default_value' => false,
          'return_format' => 'array',
          'multiple' => 0,
          'allow_null' => 0,
          'ui' => 0,
          'ajax' => 0,
          'placeholder' => '',
        ),
        array(
          'key' => 'field_64de974f84679',
          'label' => 'Button Target',
          'name' => 'for_button_target',
          'aria-label' => '',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            '_blank' => 'Blank',
            '_self' => 'Self',
          ),
          'default_value' => '',
          'return_format' => 'value',
          'allow_null' => 0,
          'other_choice' => 0,
          'layout' => 'vertical',
          'save_other_choice' => 0,
        ),
        array(
          'key' => 'field_64de95e2fab1c',
          'label' => 'Desktop',
          'name' => '',
          'aria-label' => '',
          'type' => 'tab',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'placement' => 'top',
          'endpoint' => 0,
        ),
        array(
          'key' => 'field_64de9603fab1d',
          'label' => 'Button Align',
          'name' => 'for_button_aling_desktop',
          'aria-label' => '',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'text-left' => 'Left',
            'text-center' => 'Center',
            'text-right' => 'Right',
          ),
          'default_value' => '',
          'return_format' => 'value',
          'allow_null' => 0,
          'other_choice' => 0,
          'layout' => 'vertical',
          'save_other_choice' => 0,
        ),
        array(
          'key' => 'field_64de966837dc7',
          'label' => 'Mobile',
          'name' => '',
          'aria-label' => '',
          'type' => 'tab',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'placement' => 'top',
          'endpoint' => 0,
        ),
        array(
          'key' => 'field_64de967837dc8',
          'label' => 'Button Align',
          'name' => 'for_button_aling_mobile',
          'aria-label' => '',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'text-left' => 'Left',
            'text-center' => 'Center',
            'text-right' => 'Right',
          ),
          'default_value' => '',
          'return_format' => 'value',
          'allow_null' => 0,
          'other_choice' => 0,
          'layout' => 'vertical',
          'save_other_choice' => 0,
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'block',
            'operator' => '==',
            'value' => 'for/button',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
      'show_in_rest' => 0,
    ) );
	}
}

add_action( 'init', 'register_custom_acf_fields_block_button' );