<?php
/**
 * This function records fields for the acf.
 */

function register_custom_acf_fields_section_about_us() {
    if ( function_exists( 'acf_add_local_field_group' ) ) {
        acf_add_local_field_group(
            [
                'key' => 'group_about_us',
                'title' => 'Settings',
                'fields' => [
                    [
                        'key' => 'field_about_us_tab_1',
                        'label' => 'Header',
                        'name' => 'about_us_tab_1',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_header_image_about',
                        'label' => 'Header Image',
                        'name' => 'header_image_about',
                        'type' => 'image',
                        'instructions' => 'Select an image to display as a cover on the front page (1920 x 1130] px',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,png,jpeg',
                    ],
                    [
                        'key' => 'field_about_us_tab_2',
                        'label' => 'Content',
                        'name' => 'about_us_tab_2',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_this_is_foresight',
                        'label' => 'This is Foresight',
                        'name' => 'this_is_foresight',
                        'type' => 'wysiwyg',
                        'instructions' => 'Write the content according to your preference, you can use html',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '70',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ],
                    [
                        'key' => 'field_featured_image',
                        'label' => 'Featured Image',
                        'name' => 'featured_image',
                        'type' => 'image',
                        'instructions' => 'Select image',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '30',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,png,jpeg',
                    ],
                    [
                        'key' => 'field_featured_content',
                        'label' => 'Featured content',
                        'name' => 'featured_content',
                        'type' => 'wysiwyg',
                        'instructions' => 'Write the content according to your preference, you can use html',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '70',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ],
                    [
                        'key' => 'field_featured_bg_image_about',
                        'label' => 'Featured image background',
                        'name' => 'featured_bg_image_about',
                        'type' => 'image',
                        'instructions' => 'Select an image to display as a cover on the front page (1920 x 335] px',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '30',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,png,jpeg',
                    ],
                    [
                        'key' => 'field_about_us_tab_3',
                        'label' => 'CG Foresight offer',
                        'name' => 'about_us_tab_3',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_what_does_cg_foresight_offer',
                        'label' => 'What does CG Foresight offer?',
                        'name' => 'what_does_cg_foresight_offer',
                        'type' => 'wysiwyg',
                        'instructions' => 'Write the content according to your preference, you can use html',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '70',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ],
                    [
                        'key' => 'field_background_image_about_us',
                        'label' => 'Background image',
                        'name' => 'background_image_about_us',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '30',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,png,jpeg',
                    ],
                    [
                        'key' => 'field_offers',
                        'label' => 'Offers',
                        'name' => 'offers',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => '',
                        'sub_fields' => [
                            [
                                'key' => 'field_offer_icon',
                                'label' => 'Offer icon',
                                'name' => 'offer_icon',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'return_format' => 'array',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => 'jpg,png,jpeg,svg',
                            ],
                            [
                                'key' => 'field_offer_label',
                                'label' => 'Offer label',
                                'name' => 'offer_label',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                        ],
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'page_template',
                            'operator' => '==',
                            'value' => 'page-about-foresight.php',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'acf_after_title',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => [
                    0 => 'the_content',
                    1 => 'excerpt',
                    2 => 'discussion',
                    3 => 'comments',
                    4 => 'revisions',
                    5 => 'format',
                    6 => 'page_attributes',
                    7 => 'featured_image',
                    8 => 'send-trackbacks',
                ],
                'active' => true,
                'description' => '',
            ]

        );
    }
}

add_action( 'init', 'register_custom_acf_fields_section_about_us' );