<?php
/**
 * This function records fields for the acf.
 */
function register_custom_acf_fields_section_home_page() {
	if ( function_exists( 'acf_add_local_field_group' ) ) {
		acf_add_local_field_group(
			[
				'key'                   => 'group_home_page',
				'title'                 => 'Settings',
				'fields'                => [
					[
						'key'               => 'field_home_page_tab_1',
						'label'             => 'Header',
						'name'              => 'home_page_tab_1',
						'type'              => 'tab',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'placement'         => 'top',
						'endpoint'          => 0,
					],
					[
						'key'               => 'field_home_page_backgoud_image',
						'label'             => 'Background Image',
						'name'              => 'background_image',
						'type'              => 'image',
						'instructions'      => 'Select an image to display as a cover on the front page (1920 x 946] px',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'return_format'     => 'array',
						'preview_size'      => 'thumbnail',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => 'png,jpg,jpeg',
					],
					[
						'key'               => 'field_home_page_tab_2',
						'label'             => 'Participating CGIAR Centers',
						'name'              => 'home_page_tab_2',
						'type'              => 'tab',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'placement'         => 'top',
						'endpoint'          => 0,
					],
					[
						'key'               => 'field_home_page_participants_backgoud_image',
						'label'             => 'Background Image',
						'name'              => 'participants_background_image',
						'type'              => 'image',
						'instructions'      => 'Select background image (600 x 900] px',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'return_format'     => 'array',
						'preview_size'      => 'thumbnail',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => 'png,jpg,jpeg',
					],
					[
						'key'               => 'field_home_page_participants_repeater',
						'label'             => 'Items',
						'name'              => 'participants_items',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'collapsed'         => '',
						'min'               => 0,
						'max'               => 0,
						'layout'            => 'table',
						'button_label'      => '',
						'sub_fields'        => [
							[
								'key'               => 'field_home_page_participants_image',
								'label'             => 'Image logo',
								'name'              => 'image_logo',
								'type'              => 'image',
								'instructions'      => '<b style="color:#ff5555">First image: (320 x 160) px</b> <br> Other images: (160 x 160) px',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'return_format'     => 'array',
								'preview_size'      => 'thumbnail',
								'library'           => 'all',
								'min_width'         => 150,
								'min_height'        => 150,
								'min_size'          => '',
								'max_width'         => 320,
								'max_height'        => 200,
								'max_size'          => '',
								'mime_types'        => 'png,jpg,jpeg',
							],
							[
								'key'               => 'field_home_page_participants_label',
								'name'              => 'participants_label',
								'label'             => 'Label',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '',
									'class' => '',
									'id'    => '',
								],
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '60',
							],
						],
					],
					[
						'key'               => 'field_home_page_tab_3',
						'label'             => 'Curated Search',
						'name'              => 'home_page_tab_3',
						'type'              => 'tab',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'placement'         => 'top',
						'endpoint'          => 0,
					],
					[
						'key'               => 'field_home_page_curated_search_repeater',
						'label'             => 'Slider Items',
						'name'              => 'slider_items',
						'type'              => 'repeater',
						'instructions'      => 'Add slider items',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'collapsed'         => '',
						'min'               => 0,
						'max'               => 20,
						'layout'            => 'block',
						'button_label'      => '',
						'sub_fields'        => [
							[
								'key'               => 'field_home_page_term_cured',
								'label'             => 'Term Cured',
								'name'              => 'term_cured',
								'type'              => 'taxonomy',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '30',
									'class' => '',
									'id'    => '',
								],
								'taxonomy'          => 'post_tag',
								'field_type'        => 'select',
								'allow_null'        => 0,
								'add_term'          => 0,
								'save_terms'        => 0,
								'load_terms'        => 0,
								'return_format'     => 'object',
								'multiple'          => 0,
							],
							[
								'key'               => 'field_home_page_term_image',
								'label'             => 'Term Image',
								'name'              => 'term_image',
								'type'              => 'image',
								'instructions'      => 'Select image (150 x 150) px',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => [
									'width' => '30',
									'class' => '',
									'id'    => '',
								],
								'return_format'     => 'id',
								'preview_size'      => 'thumbnail',
								'library'           => 'all',
								'min_width'         => 150,
								'min_height'        => 150,
								'min_size'          => '',
								'max_width'         => 150,
								'max_height'        => 150,
								'max_size'          => '',
								'mime_types'        => 'jpg,png,jpeg',
							],
						],
					],
					[
						'key'               => 'field_home_page_tab_4',
						'label'             => 'Contact Us',
						'name'              => 'home_page_tab_4',
						'type'              => 'tab',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'placement'         => 'top',
						'endpoint'          => 0,
					],
					[
						'key'               => 'field_home_page_contact_us',
						'name'              => 'page_contact_us',
						'label'             => 'Select a contact page',
						'type'              => 'page_link',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'post_type'         => [
							0 => 'page',
						],
						'allow_null'        => 0,
						'allow_archives'    => 1,
						'multiple'          => 0,
					],
					[
						'key'               => 'field_home_page_contact_us_background',
						'name'              => 'contact_us_background',
						'label'             => 'Background image',
						'type'              => 'image',
						'instructions'      => 'Select image (1950 × 648) px',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'return_format'     => 'array',
						'preview_size'      => 'thumbnail',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => 'png,jpg,jpeg',
					],
				],
				'location'              => [
					[
						[
							'param'    => 'page_type',
							'operator' => '==',
							'value'    => 'front_page',
						],
					],
				],
				'menu_order'            => 0,
				'position'              => 'acf_after_title',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => [
					0 => 'the_content',
					1 => 'excerpt',
					2 => 'discussion',
					3 => 'comments',
					4 => 'revisions',
					5 => 'format',
					6 => 'page_attributes',
					7 => 'featured_image',
					8 => 'send-trackbacks',
				],
				'active'                => true,
				'description'           => '',
			]
		);
	}
}

add_action( 'init', 'register_custom_acf_fields_section_home_page' );
