name: Deploy to Foresight WP Engine
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Build Wordpress Theme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Build   
        run: |
          npm install
          npm install --global gulp-cli
          gulp build
      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
          name: wp-build
          path: build/*

  deploy-dev:
    name: Deploy to Development
    environment:
      name: Development
      url: https://devcgforesight.wpengine.com
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Downloading build Artifact  
        uses: actions/download-artifact@v3
        with:
          name: wp-build
      - name: Display structure of downloading files
        run: |
          tree
      
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: git.wpengine.com 

      - name: Deploy to WP Engine
        run: |
          # REMOVE GIT FROM BUILD DIR SO WE CAN PIPE TO WPENGINE'S GIT
          rm -rf .git
          # ADD FAKE USER DETAILS, OTHERWISE GIT COMPLAINS
          git config --global user.email "devops@cafetosoftware.com"
          git config --global user.name "DevOps Cafeto Team"
          # COMMIT THE COMPLETED BUILD ARTEFACT TO WPENGINE'S GIT
          cd .. && mkdir deploy && cd deploy/ && git clone ${{ secrets.GIT_REMOTE }} .
          rm -rf * && mkdir -p wp-content/themes
          mv /home/runner/work/foresight-theme/foresight-theme/foresight-cgiar wp-content/themes
          git add . && git commit -m "Deploy from GitHub Actions"
          git push origin master

  deploy-staging:
    name: Deploy to Staging
    environment:
      name: Staging
      url: stgcgforesight.wpengine.com
    needs: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Downloading build Artifact  
        uses: actions/download-artifact@v3
        with:
          name: wp-build
      - name: Display structure of downloading files
        run: |
          tree
      
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: git.wpengine.com 

      - name: Deploy to WP Engine
        run: |
          # REMOVE GIT FROM BUILD DIR SO WE CAN PIPE TO WPENGINE'S GIT
          rm -rf .git
          # ADD FAKE USER DETAILS, OTHERWISE GIT COMPLAINS
          git config --global user.email "devops@cafetosoftware.com"
          git config --global user.name "DevOps Cafeto Team"
          # COMMIT THE COMPLETED BUILD ARTEFACT TO WPENGINE'S GIT
          cd .. && mkdir deploy && cd deploy/ && git clone ${{ secrets.GIT_REMOTE }} .
          rm -rf * && mkdir -p wp-content/themes
          mv /home/runner/work/foresight-theme/foresight-theme/foresight-cgiar wp-content/themes
          git add . && git commit -m "Deploy from GitHub Actions"
          git push origin master

  deploy-prod:
    name: Deploy to Production
    environment:
      name: Production
      url: foresight.cgiar.org
    needs: deploy-staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Downloading build Artifact  
        uses: actions/download-artifact@v3
        with:
          name: wp-build
      - name: Display structure of downloading files
        run: |
          tree
      
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: git.wpengine.com 

      - name: Deploy to WP Engine
        run: |
          # REMOVE GIT FROM BUILD DIR SO WE CAN PIPE TO WPENGINE'S GIT
          rm -rf .git
          # ADD FAKE USER DETAILS, OTHERWISE GIT COMPLAINS
          git config --global user.email "devops@cafetosoftware.com"
          git config --global user.name "DevOps Cafeto Team"
          # COMMIT THE COMPLETED BUILD ARTEFACT TO WPENGINE'S GIT
          cd .. && mkdir deploy && cd deploy/ && git clone ${{ secrets.GIT_REMOTE }} .
          rm -rf * && mkdir -p wp-content/themes
          mv /home/runner/work/foresight-theme/foresight-theme/foresight-cgiar wp-content/themes
          git add . && git commit -m "Deploy from GitHub Actions"
          git push origin master