name: Deploy to WP Engine
on:
  push:
    branches:
      - task/*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Build   
        run: |
          ls
          ls -alh /
          pwd
          npm install
          npm install --global gulp-cli
          gulp build
          ls
          ls build
      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
          name: wp-build
          path: build/*

  deploy-dev:
    name: Deploy to Development
    environment:
      name: Development
      url: https://devcgforesight.wpengine.com
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Downloading build Artifact  
        uses: actions/download-artifact@v3
        with:
          name: wp-build
      - name: Display structure of downloading files
        run: |
          ls
          pwd
          ls -R
      
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: git.wpengine.com 

      - name: Set up Git
        run: |
          git config user.email "devops@cafetosoftware.com"
          git config user.name "devcgforesight-github-actions"

      - name: Deploy to WP Engine
        run: |
          # REMOVE GIT FROM BUILD DIR SO WE CAN PIPE TO WPENGINE'S GIT
          rm -rf .git
          # COMMIT THE COMPLETED BUILD ARTIFACT TO WPENGINE'S GIT
          mkdir deploy && cd deploy/
          git clone ${{ secrets.GIT_REMOTE }} .
          ls -alh
          tree
          pwd
          rm -rf *
          mkdir -p wp-content/themes
          mv /home/runner/work/foresight-theme/foresight-theme/foresight-cgiar/* wp-content/themes
          git add .
          git commit -m 'Deploy from GitHub Actions'
          git push origin master