name: Deploy to WP Engine
on:
  push:
    branches:
      - task/*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Build   
        run: |
          ls
          pwd
          npm install
          npm install --global gulp-cli
          gulp build
        # env:
        #   NODE_ENV: production
        # Modify the artifacts paths to match your project structure
        # Make sure the 'build/**' pattern matches the desired files
        # that you want to store as artifacts.
        # For example, if you want to include the 'wp-content/themes' directory,
        # you can use 'build/wp-content/themes/**'
        # Add more artifact paths if needed.
        # artifacts:
        #   paths:
        #    - build/**

  deploy:
    name: Deploy to Development
    environment:
      name: Development
      url: https://devcgforesight.wpengine.com
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  

      - name: Set up Git
        run: |
          git config user.email "devops@cafetosoftware.com"
          git config user.name "devcgforesight-github-actions"

      - name: Deploy to WP Engine
        run: |
          # REMOVE GIT FROM BUILD DIR SO WE CAN PIPE TO WPENGINE'S GIT
          rm -rf .git
          # COMMIT THE COMPLETED BUILD ARTIFACT TO WPENGINE'S GIT
          mkdir deploy && cd deploy/
          git clone ${{ secrets.GIT_REMOTE }} .
          rm -rf *
          mkdir -p wp-content/themes
          mv /home/runner/work/foresight-theme/foresight-theme/build/* wp-content/themes
          git add .
          git commit -m 'Deploy from GitHub Actions'
          git push origin master