name: Deploy to Foresight WP Engine
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Build Wordpress Theme
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14  

      - name: Build instantsearch
        run: |
            pwd
            ls
            cd foresight-instantsearch
            npm install
            npm run build
            tree ..
            cd ../foresight-plugin-algolia/src

      - name: Build plugins
        run: |
            pwd
            # INSTALL COMPOSER
            sudo apt update
            sudo apt install php-cli unzip -y
            cd ~
            curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
            HASH=`curl -sS https://composer.github.io/installer.sig`
            php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
            composer update
            cd ..
            npm install
            npm install --global gulp-cliate
            gulp build
      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
          name: plugin-build
          path: foresight-plugin-algolia/build/*

      - name: Build Theme  
        run: |
          cd foresight-theme
          npm install
          npm install --global gulp-cli
          gulp build
      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
          name: theme-build
          path: foresight-theme/build/*

  deploy-dev:
    name: Deploy to Development
    environment:
      name: Development
      url: https://devcgforesight.wpengine.com
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Downloading build Artifact  
        uses: actions/download-artifact@v3
        with:
          name: wp-build
      - name: Display structure of downloading files
        run: |
          tree

      # - uses: ./foresight-cgiar/
      #   name: Security Scan
      #   with:
      #     api-provider: 'wpscan'
      #     api-token: ${{ secrets.WPSCAN_API_TOKEN }}
      #     type: 'theme'
      #     name: 'Foresight-theme'
      
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: git.wpengine.com 

      - name: Deploy to WP Engine
        run: |
          # REMOVE GIT FROM BUILD DIR SO WE CAN PIPE TO WPENGINE'S GIT
          rm -rf .git
          # ADD FAKE USER DETAILS, OTHERWISE GIT COMPLAINS
          git config --global user.email "devops@cafetosoftware.com"
          git config --global user.name "DevOps Cafeto Team"
          # COMMIT THE COMPLETED BUILD ARTEFACT TO WPENGINE'S GIT
          cd .. && mkdir deploy && cd deploy/ && git clone ${{ secrets.GIT_REMOTE }} .
          rm -rf * && mkdir -p wp-content/themes && mkdir -p wp-content/plugins
          mv /home/runner/work/foresight/foresight-theme/foresight-cgiar wp-content/themes
          mv /home/runner/work/foresight/foresight-theme/foresight-plugin-algolia wp-content/plugins
          git add . && git commit -m "Deploy from GitHub Actions"
          git push origin master
          tree ..

  deploy-staging:
    name: Deploy to Staging
    environment:
      name: Staging
      url: stgcgforesight.wpengine.com
    needs: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Downloading build Artifact  
        uses: actions/download-artifact@v3
        with:
          name: wp-build
      - name: Display structure of downloading files
        run: |
          tree
      
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: git.wpengine.com 

      - name: Deploy to WP Engine
        run: |
          # REMOVE GIT FROM BUILD DIR SO WE CAN PIPE TO WPENGINE'S GIT
          rm -rf .git
          # ADD FAKE USER DETAILS, OTHERWISE GIT COMPLAINS
          git config --global user.email "devops@cafetosoftware.com"
          git config --global user.name "DevOps Cafeto Team"
          # COMMIT THE COMPLETED BUILD ARTEFACT TO WPENGINE'S GIT
          cd .. && mkdir deploy && cd deploy/ && git clone ${{ secrets.GIT_REMOTE }} .
          rm -rf * && mkdir -p wp-content/themes
          mv /home/runner/work/foresight-theme/foresight-theme/foresight-cgiar wp-content/themes
          git add . && git commit -m "Deploy from GitHub Actions"
          git push origin master
  deploy-prod:
    name: Deploy to Production
    environment:
      name: Production
      url: foresight.cgiar.org
    needs: deploy-staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Downloading build Artifact  
        uses: actions/download-artifact@v3
        with:
          name: wp-build
      - name: Display structure of downloading files
        run: |
          tree
      
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: git.wpengine.com 

      - name: Deploy to WP Engine
        run: |
          # REMOVE GIT FROM BUILD DIR SO WE CAN PIPE TO WPENGINE'S GIT
          rm -rf .git
          # ADD FAKE USER DETAILS, OTHERWISE GIT COMPLAINS
          git config --global user.email "devops@cafetosoftware.com"
          git config --global user.name "DevOps Cafeto Team"
          # COMMIT THE COMPLETED BUILD ARTEFACT TO WPENGINE'S GIT
          cd .. && mkdir deploy && cd deploy/ && git clone ${{ secrets.GIT_REMOTE }} .
          rm -rf * && mkdir -p wp-content/themes
          mv /home/runner/work/foresight-theme/foresight-theme/foresight-cgiar wp-content/themes
          git add . && git commit -m "Deploy from GitHub Actions"
          git push origin master